blank_issues_enabled: false
contact_links:
  - name: paperlesspaper Support
    url: https://paperlesspaper.de/posts/contact
    about: For issues with your paperlesspaper device or account, contact paperlesspaper directly.
